/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#331100",
        "secondary-container": "#90efef",
        "surface-container": "rgba(255, 255, 255, 0.4)",
        "on-secondary-fixed": "#002020",
        "tertiary-fixed-dim": "#ffb68f",
        "tertiary-fixed": "#ffdbca",
        "surface": "transparent",
        "secondary-fixed": "#93f2f2",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#2d3c9c",
        "on-surface-variant": "#454652",
        "on-primary": "#ffffff",
        "on-background": "#171c1f",
        "surface-container-low": "rgba(255, 255, 255, 0.5)",
        "on-secondary-container": "#006e6e",
        "error-container": "#ffdad6",
        "surface-variant": "#dfe3e7",
        "on-primary-fixed": "#000d5f",
        "surface-container-lowest": "rgba(255, 255, 255, 0.6)",
        "primary-fixed-dim": "#bbc3ff",
        "on-tertiary-fixed-variant": "#773200",
        "error": "#ba1a1a",
        "inverse-primary": "#bbc3ff",
        "inverse-surface": "#2c3134",
        "surface-container-highest": "rgba(255, 255, 255, 0.2)",
        "background": "transparent",
        "on-error-container": "#93000a",
        "tertiary": "#582300",
        "secondary-fixed-dim": "#76d6d5",
        "primary-container": "#303f9f",
        "outline-variant": "#c6c5d4",
        "primary": "#142588",
        "on-secondary-fixed-variant": "#004f4f",
        "on-secondary": "#ffffff",
        "surface-tint": "#4755b6",
        "primary-fixed": "#dfe0ff",
        "inverse-on-surface": "#edf1f5",
        "surface-dim": "#d6dade",
        "on-surface": "#171c1f",
        "tertiary-container": "#7b3400",
        "surface-bright": "transparent",
        "on-primary-container": "#aab4ff",
        "secondary": "#006a6a",
        "outline": "#767683",
        "surface-container-high": "rgba(255, 255, 255, 0.3)",
        "on-tertiary-container": "#ffa26e"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
